### PR TITLE
Scope JSON to global ruby ::JSON, prevents conflicts with Sinatra::JSON

### PR DESCRIPTION
**Pull request by gerbal**

### CODE REVIEW

**Comment by brennovich** [comment]
Hey, can this be merged? I'm having this issues too, and anyone using `sinatra/json` extension will face it as well.

**Comment by gerbal** [comment]
@archiloque could you merge this mate?

**Comment by rbroemeling** [comment]
@gerbal The PR as written covers the JSON usage in lib/sinatra/swagger-exposer/processing/swagger-response-processor.rb, but not the JSON usage in lib/sinatra/swagger-exposer/processing/swagger-request-processor.rb. Perhaps it should be updated before merged?

Credit to @brennovich for seeing this, I just noticed the difference between this PR and his work at https://github.com/brennovich/sinatra-swagger-exposer/commit/dd38ee5148197b5da2da2d82b7e48043d90f39d7 .

**Comment by gerbal** [comment]
We could just merge in brennovich@dd38ee5

**Comment by archiloque** [comment]
Sorry my notifications were broken, I'm having a look at it this week-end.

**Pull request merged**
